export type Dept = {
  slug: string;
  emoji: string;
  category: string;
  name: string;
  tagline: string;
  pitch: string;
  outcomes: string[];
  features: string[];
  pricing: { tier: string; price: string; includes: string[] }[];
  proof: string;
  caseStudyHook: string;
  alsoBuy: string[]; // related dept slugs
};

export const DEPTS: Record<string, Dept> = {
  "marketing": {
    slug: "marketing",
    emoji: "📢",
    category: "Get more leads",
    name: "AI Marketing",
    tagline: "A strategist, a planner, and an analyst — all running 24/7 for less than a part-time hire.",
    pitch: "Most small businesses don't need a marketing 'campaign.' They need a marketing operation that runs every day, learns what works, kills what doesn't, and reports back. That's what AI Marketing does.",
    outcomes: ["More qualified leads month-over-month", "A real plan instead of random posting", "You see what's working — and what isn't"],
    features: [
      "Weekly marketing plan tied to your business goals",
      "Multi-channel campaign coordination (social, email, ads, content)",
      "A/B tests run automatically — winners scale, losers die",
      "Competitor tracking — what's working in your industry, right now",
      "Weekly performance digest delivered Monday morning",
      "Strategist AI you can chat with anytime (DJ relay)",
    ],
    pricing: [{ tier: "AI Marketing", price: "$497/mo", includes: ["Weekly plan", "Multi-channel coordination", "A/B testing", "Competitor watch", "Monday digest"] }],
    proof: "Crest Air's lead flow went from 0 web leads to 12+/week in 30 days running just AI Marketing + AI Social.",
    caseStudyHook: "See how Crest Air went from invisible to 12 leads/week",
    alsoBuy: ["social-media", "advertising", "content"],
  },
  "advertising": {
    slug: "advertising",
    emoji: "🎯",
    category: "Get more leads, faster",
    name: "AI Advertising",
    tagline: "Google, Meta, TikTok ads run by an AI that never wastes a click and never burns budget on losers.",
    pitch: "Paid ads are the fastest path to leads — and the fastest path to setting $5,000 on fire. AI Advertising builds, launches, watches, and kills campaigns based on real performance data. You set the budget. The AI handles everything else.",
    outcomes: ["Lower cost per lead vs DIY or freelancer", "Budget never wasted on what's not working", "You see exactly which dollars made the phone ring"],
    features: [
      "Google Ads + Meta Ads + TikTok Ads under one roof",
      "Auto-build creative variants (copy + image + video) from your brand kit",
      "Auto-kill ads under your target CPL within 48 hours",
      "Conversion tracking wired end-to-end (ad → form → CRM → revenue)",
      "Re-targeting + lookalike audiences set up automatically",
      "Weekly ROAS report — and a quarterly strategy reset",
    ],
    pricing: [{ tier: "AI Advertising", price: "$697/mo + ad spend", includes: ["All ad platforms managed", "Creative auto-built", "Auto-kill rules", "End-to-end attribution", "ROAS reporting"] }],
    proof: "Most clients see CPL drop 30-50% in the first 60 days vs. what they were paying a freelance manager.",
    caseStudyHook: "How AI Advertising builds ads while you sleep",
    alsoBuy: ["marketing", "social-media", "sales-crm"],
  },
  "social-media": {
    slug: "social-media",
    emoji: "📱",
    category: "Show up online consistently",
    name: "AI Social Media",
    tagline: "Posts, reels, stories, captions, hashtags — every channel, every day, no employee required.",
    pitch: "You know you should be posting daily on Instagram, TikTok, Facebook, GBP, LinkedIn — but who has time? AI Social Media handles the entire production pipeline. You approve what ships. Done.",
    outcomes: ["You stay top-of-mind without doing the work", "Algorithm-friendly cadence on every platform", "Real engagement, not vanity metrics"],
    features: [
      "Daily posts on FB, IG, TikTok, YouTube, GBP, LinkedIn — auto-generated, brand-on-voice",
      "AI Image gen + AI Video gen + AI Thumbnail maker built in",
      "Captions + hashtags + CTAs written per platform (different copy for IG vs FB vs TikTok)",
      "Content calendar you approve once a week — 5 minutes",
      "Automatic engagement: AI responds to comments + DMs in your tone",
      "Performance digest tells you what to make more of",
    ],
    pricing: [{ tier: "AI Social Media", price: "$397/mo", includes: ["6 platforms daily", "AI creative production", "Per-platform captions", "Auto engagement", "Weekly approval queue"] }],
    proof: "Crest Air went from inactive social accounts to 3 posts/week across 6 platforms — all approved by the owner in <30 min/week.",
    caseStudyHook: "Watch a week of social content built in 15 minutes",
    alsoBuy: ["content", "marketing", "advertising"],
  },
  "content": {
    slug: "content",
    emoji: "✍️",
    category: "Show up online consistently",
    name: "AI Content",
    tagline: "Blog posts, email newsletters, SMS campaigns, video scripts — written in your voice, on schedule.",
    pitch: "Content is the slowest, most expensive part of marketing. Hire a writer at $5k/mo, get 4 blog posts. AI Content gives you 4 posts a week, plus the email, plus the SMS, plus the YouTube script — for a fraction of one writer's salary.",
    outcomes: ["Real long-form content that ranks", "Newsletter that actually goes out weekly", "SMS campaigns that don't feel spammy"],
    features: [
      "AI Blog Writer — 800-1500 word posts, SEO-optimized, in your brand voice",
      "AI Email Writer — newsletters, sequences, broadcasts",
      "AI SMS Writer — short, compliant, conversion-focused",
      "AI Video Script — for YouTube + reels + TikTok",
      "Brand Voice trained on your existing copy (or built fresh with you)",
      "Approval queue — nothing ships without your green light",
    ],
    pricing: [{ tier: "AI Content", price: "$347/mo", includes: ["Weekly blog post", "Weekly email", "SMS as needed", "Video scripts", "Brand voice", "Approval queue"] }],
    proof: "Crest Air ships 4 pieces of long-form content per week — blog, email, two scripts — all on autopilot.",
    caseStudyHook: "See a week of AI Content production",
    alsoBuy: ["social-media", "web", "marketing"],
  },
  "web": {
    slug: "web",
    emoji: "🌐",
    category: "Have a website that actually converts",
    name: "AI Web",
    tagline: "A website that updates itself, ranks itself, and turns visitors into leads — without a developer on call.",
    pitch: "Your website should be a salesperson that works 24/7. Most small business sites are brochures that haven't been updated in two years. AI Web rebuilds your site to convert, then keeps it fresh forever.",
    outcomes: ["Site that ranks for what you actually sell", "Pages that convert visitors to leads", "Updates ship in minutes, not weeks"],
    features: [
      "Full Next.js site on Vercel (same stack as bizzycube.com)",
      "AI Page Builder — describe a page in plain English, get a designed page",
      "AI Search optimization (schema.org, llms.txt, AI crawler permits — so ChatGPT/Claude/Perplexity recommend you)",
      "Forms wired to your CRM with lead routing",
      "Blog auto-publishes from AI Content",
      "Custom domain + auto-SSL + global CDN + one-click rollback",
    ],
    pricing: [{ tier: "AI Web", price: "$497/mo", includes: ["Full site rebuild", "AI Page Builder", "AI Search SEO", "Forms + CRM wiring", "Domain + SSL + hosting"] }],
    proof: "crestairaz.com was rebuilt in 30 days — ranks for 'Tucson HVAC' on AI search engines, converts at 3.8%.",
    caseStudyHook: "See a site rebuild from scratch in 30 days",
    alsoBuy: ["content", "advertising", "marketing"],
  },
  "sales-crm": {
    slug: "sales-crm",
    emoji: "💬",
    category: "Stop losing leads",
    name: "AI Sales & CRM",
    tagline: "Every lead captured, qualified, routed, and followed up — in seconds, not hours.",
    pitch: "The #1 reason small businesses lose deals is slow follow-up. The average web lead waits 47 hours for a callback. AI Sales & CRM captures, qualifies, and routes the lead to you in under 90 seconds — then keeps following up if you don't respond.",
    outcomes: ["No lead ever sits in an inbox", "AI SDR follows up like a tireless rep", "You see the whole pipeline in one place"],
    features: [
      "Capture from web forms, calls, social DMs, Google Business Profile",
      "Auto-qualify with custom rules per lead source",
      "Route to the right person (or team) instantly — push + SMS + chat",
      "AI SDR follow-up sequences via SMS + email + voice",
      "Pipeline dashboard with hot lead alerts",
      "Replaces or sits alongside HCP, GHL, Salesforce — your choice",
    ],
    pricing: [{ tier: "AI Sales & CRM", price: "$447/mo", includes: ["All capture sources", "Qualify + route in <90s", "AI SDR follow-up", "Pipeline dashboard", "CRM integration"] }],
    proof: "Crest Air's Melissa gets a push notification with name + phone + intent every time a web lead lands. Zero leads lost since launch.",
    caseStudyHook: "Watch a lead go from form to push notification in 60 seconds",
    alsoBuy: ["ai-receptionist", "marketing", "advertising"],
  },
  "ai-receptionist": {
    slug: "ai-receptionist",
    emoji: "📞",
    category: "Answer the phone 24/7",
    name: "AI Receptionist",
    tagline: "Real voice. Real understanding. Real customers never hit voicemail again.",
    pitch: "Half of small business calls go to voicemail. Half of those callers don't call back. AI Receptionist answers every call in your business voice, qualifies the caller, books the appointment, and routes hot leads to your phone in real time.",
    outcomes: ["Zero missed calls, 24/7", "Hot leads texted to you instantly", "Customers think they're talking to a real human"],
    features: [
      "Custom voice + script trained on your business",
      "Books appointments directly to your calendar",
      "Detects emergency / high-intent calls and texts you immediately",
      "After-hours coverage with intelligent message-taking",
      "Spanish + English (more languages available)",
      "Replaces a $40k/yr receptionist or a $300/mo answering service",
    ],
    pricing: [{ tier: "AI Receptionist", price: "$297/mo + per-minute", includes: ["Custom voice", "Calendar booking", "Hot lead routing", "After hours", "Multilingual"] }],
    proof: "Crest Air's AI receptionist on (520) 999-8088 handles intake while the owner is on a roof.",
    caseStudyHook: "Hear the Crest Air AI receptionist take a real call",
    alsoBuy: ["sales-crm", "marketing", "onboarding"],
  },
  "accounting": {
    slug: "accounting",
    emoji: "📊",
    category: "Keep books clean without a bookkeeper",
    name: "AI Accounting",
    tagline: "Books reconciled weekly. P&L always current. Tax lots tracked. Bookkeeper-grade work for less than a part-timer.",
    pitch: "Most small businesses know their books are a mess but can't justify a $3,000/mo bookkeeper. AI Accounting categorizes every transaction, reconciles weekly, runs P&L on demand, and hands your CPA a clean year-end package.",
    outcomes: ["Books always current — not 'I'll get to it'", "P&L on demand from any device", "Tax-ready handoff to your CPA"],
    features: [
      "Bank + credit card auto-categorization (rules + AI)",
      "Weekly reconciliation report",
      "Monthly P&L, cash flow, balance sheet — auto-generated",
      "Tax lot tracking for any investing or inventory",
      "1099 + W-2 prep handoff",
      "Slack/email summary every Friday: what came in, what went out, what to watch",
    ],
    pricing: [{ tier: "AI Accounting", price: "$397/mo", includes: ["Auto-categorization", "Weekly reconciliation", "Monthly statements", "Tax prep handoff", "Friday summary"] }],
    proof: "Replaces $3-5k/mo of bookkeeper time. Pairs with a CPA for year-end.",
    caseStudyHook: "Take a tour of AI Accounting's Friday summary",
    alsoBuy: ["sales-crm", "ai-receptionist", "onboarding"],
  },
  "onboarding": {
    slug: "onboarding",
    emoji: "🤝",
    category: "Get every customer to value, fast",
    name: "AI Onboarding",
    tagline: "Every new customer walked through setup, trained, and converted to a long-term retain — automatically.",
    pitch: "You closed the deal. Now what? Onboarding is the difference between a 6-month customer and a 6-year customer. AI Onboarding sequences every new customer through setup, education, milestones, and check-ins — without you lifting a finger.",
    outcomes: ["Higher activation rate", "Lower churn in the critical first 90 days", "More upsells from engaged customers"],
    features: [
      "Onboarding sequence triggered the moment a deal closes",
      "Drip emails + SMS + in-app messages timed to user behavior",
      "Live milestone tracking (e.g. 'they hit their 3rd login this week')",
      "AI check-in calls or texts at days 7, 14, 30, 60, 90",
      "Auto-flag customers at risk of churn so you can intervene",
      "Survey + NPS collection + summary digest",
    ],
    pricing: [{ tier: "AI Onboarding", price: "$297/mo", includes: ["Trigger-based sequence", "Multi-channel drip", "Milestone tracking", "Check-in calls", "Churn risk alerts"] }],
    proof: "Onboarding sequences typically lift 90-day retention by 15-25% in the first quarter live.",
    caseStudyHook: "See an onboarding sequence go live in 24 hours",
    alsoBuy: ["sales-crm", "ai-receptionist", "marketing"],
  },
};

export const DEPT_ORDER = ["marketing", "advertising", "social-media", "content", "web", "sales-crm", "ai-receptionist", "accounting", "onboarding"];

export const CATEGORIES = [
  { name: "Get more leads", emoji: "🎯", depts: ["marketing", "advertising"] },
  { name: "Show up online", emoji: "📱", depts: ["social-media", "content", "web"] },
  { name: "Convert + keep customers", emoji: "💬", depts: ["sales-crm", "ai-receptionist", "onboarding"] },
  { name: "Run the back office", emoji: "📊", depts: ["accounting"] },
];
